CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');

CREATE TABLE uploaded_videos (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    rating star_rating
);