CREATE TABLE uploaded_video (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL,
    title TEXT,
    content TEXT,
    video_url TEXT NOT NULL
);